baseurl = "https://hankpeng.netlify.com/"
title = "Hank Peng"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Hank Peng"
    description = "Hank Peng's personal website"
    keywords = "blog,developer,personal"
    info = "Full Stack DevOps and Magician"
    avatarurl = "images/avatar.jpg"
    footercontent = "Enter a text here."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/HankPPeng"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/WeihongPPeng"
[[params.social]]
    name = "Wechat"
    icon = "fab fa-weixin"
    weight = 3
    url = "https://www.linkedin.com/in/johndoe/"


[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About Me"
        weight = 1
        url = "about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "posts/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "projects/"

        [[languages.en.menu.main]]
        name = "Contact Me"
        weight = 4
        url = "contact/"