baseurl = "https://hankpeng.netlify.com/"
title = "Hank Peng"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "hank-peng"

[params]
    author = "Hank Peng"
    description = "Hank Peng's personal website"
    keywords = "blog,developer,personal"
    info = "Always believe that life is full of beauty."
    avatarurl = "images/avatar2.jpg"
    footercontent = "Try not to become a man of success. Rather become a man of value. —Albert Einstein"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/HankPPeng"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/WeihongPPeng"
[[params.social]]
    name = "Wechat"
    icon = "fab fa-weixin"
    weight = 3
    url = "https://github.com/HankPPeng/HankPeng.com/blob/master/images/My%20Wechat%20QR%20code.jpg?raw=true"


[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About Me"
        weight = 1
        url = "about/"
        
        [[languages.en.menu.main]]
        name = "Publications"
        weight = 2
        url = "publications/"
        
        [[languages.en.menu.main]]
        name = "Research"
        weight = 3
        url = "research/"
        
        [[languages.en.menu.main]]
        name = "Posts"
        weight = 4
        url = "posts/"

        [[languages.en.menu.main]]
        name = "Contact"
        weight = 5
        url = "contact/"